# Moduły

Jedną z największych zalet Pythona jest jego modularność. Podstawowy Python zawiera tylko napotrzebniejsze funkcje, natomiast jego możliwości są znacznie rozszerzone poprzez _moduły_. Moduł to nic innego jak zbiór funkcji służących do realizacji określonych czynności. Wiele modułów dostępnych jest razem z podstawową instalacją Pythona (<https://docs.python.org/3/py-modindex.html>), jeszcze więcej zanistalowanych jest domyślnie wraz z Anacondą (<https://docs.anaconda.com/anaconda/packages/old-pkg-lists/4.3.1/py35/>). Możesz też instalować dodatkowe moduły poprzez Anacondę (<https://conda.io/docs/user-guide/tasks/manage-pkgs.html>).

## Przykład - moduł `pandas`

Jeżeli dany moduł jest zainstalowany na twoim komputerze, musisz go zaimportować zanim skorzystasz z jego funkcji. Zaimportujemy teraz moduł, który służy do analizy danych w Pythonie. Nie mamy czasu na tym kursie aby opowiedzieć o nim w szczegółach, posłuży on nam tylko jako ilustracja _modularności_ Pythona. Aby zaimportować moduł stosujemy słowo kluczowe `import` i nazwę modułu. Aby uniknąć konfliktów w nazwach funkcji najczęściej podajemy też krótką nazwę, po której identyfikować będziemy funkcje z danego modułu. Zwyczajowo dla `pandas` jest to `pd`. Całość wygląda tak:

In [1]:
import pandas as pd

Dzięki tej linijce zaimportowane i dostępne są wszystkie funkcje odstępne w module `pandas`. Żeby z nich skorzystać, musimy ich nazwy poprzedzić prefiksem `pd.`. Skorzystamy teraz z funkcji `read_csv`, która otwiera plik `csv` znajdujący się na dysku, odczytuje go i umieszcza w czymś, co nazywa się `pandas dataframe` - strukturze służącej do przechowywania danych w formie tabel. Załadujemy plik `movies.csv` dostępny w repo przedmiotu w folderze `data`. W pliku tym znajduje się kompletna baza filmów z serwisu <http://imdb.com> aż do 2005 roku. W argumencie funkcji musimy podać właściwą ścieżkę dostepu do pliku.

In [2]:
filmy = pd.read_csv('data/movies.csv')

Jeśli teraz spróbujemy wyświetlić zmienną filmy, Jupyter pokaże nam ładnie sformatowaną tabelę. Zwróć uwagę na ostatnią linijkę. Ile mamy filmów w naszym zbiorze danych?

In [3]:
filmy

,title,year,length,budget,rating,votes,mpaa,Action,Animation,Comedy,Drama,Documentary,Romance,Short
0,$,1971,121,NaN,6.4,348,NaN,0,0,1,1,0,0,0
1,$1000 a Touchdown,1939,71,NaN,6.0,20,NaN,0,0,1,0,0,0,0
2,$21 a Day Once a Month,1941,7,NaN,8.2,5,NaN,0,1,0,0,0,0,1
3,"$40,000",1996,70,NaN,8.2,6,NaN,0,0,1,0,0,0,0
4,"$50,000 Climax Show, The",1975,71,NaN,3.4,17,NaN,0,0,0,0,0,0,0
5,$pent,2000,91,NaN,4.3,45,NaN,0,0,0,1,0,0,0
6,$windle,2002,93,NaN,5.3,200,R,1,0,0,1,0,0,0
7,'15',2002,25,NaN,6.7,24,NaN,0,0,0,0,1,0,1
8,'38,1987,97,NaN,6.6,18,NaN,0,0,0,1,0,0,0
9,'49-'17,1917,61,NaN,6.0,51,NaN,0,0,0,0,0,0,0
10,'68,1988,99,NaN,5.4,23,NaN,0,0,0,1,0,0,0
11,'94 du bi dao zhi qing,1994,96,NaN,5.9,53,NaN,0,0,0,0,0,0,0
12,"'?' Motorist, The",1906,10,NaN,7.0,44,NaN,0,0,1,0,0,0,1
13,'A',1965,10,NaN,6.7,11,NaN,0,0,0,0,0,0,1
14,'A' gai waak,1983,106,NaN,7.1,1259,PG-13,1,0,1,0,0,0,0
15,'A' gai waak juk jaap,1987,101,NaN,7.2,614,PG-13,1,0,1,0,0,0,0
16,'Breaker' Morant,1980,107,NaN,7.9,2718,NaN,0,0,0,1,0,0,0
17,'Bullitt': Steve McQueen's Commitment to Reality,1968,10,NaN,6.6,37,NaN,0,0,0,0,1,0,1
18,'Crocodile' Dundee II,1988,110,NaN,5.0,7252,NaN,1,0,1,0,0,0,0
19,'E',1981,7,NaN,8.6,15,NaN,0,1,1,0,0,0,1
20,'El Chicko' - der Verdacht,1995,90,NaN,3.9,10,NaN,0,0,1,0,0,0,0
21,'G' Men,1935,85,450000.0,7.2,281,NaN,0,0,0,1,0,0,0
22,'Gator Bait,1974,88,NaN,3.5,100,NaN,1,0,0,1,0,0,0
23,'Gator Bait II: Cajun Justice,1988,95,NaN,3.1,54,NaN,0,0,0,0,0,0,0
24,"'High Sign', The",1921,18,NaN,7.8,145,NaN,0,0,1,0,0,0,1
25,'Hukkunud Alpinisti' hotell,1979,80,NaN,7.7,45,NaN,0,0,0,0,0,0,0
26,"'Hyp-Nut-Tist', The",1935,6,NaN,6.2,18,NaN,0,1,1,0,0,0,1
27,'I Do...',1989,86,NaN,6.2,10,NaN,0,0,0,0,0,0,0
28,'I Know Where I'm Going!',1945,92,NaN,7.7,825,NaN,0,0,0,1,0,1,0
29,'Java Madness' formerly titled 'Coffee Madness',1995,7,NaN,6.8,10,NaN,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58758,"Zwoele zomeravond, Een",1982,95,NaN,6.4,13,NaN,0,0,0,0,0,0,0
58759,Zwolnieni z zycia,1992,90,NaN,6.9,9,NaN,0,0,0,0,0,0,0
58760,Zycie jako smiertelna choroba przenoszona drog...,2000,99,NaN,7.0,97,NaN,0,0,0,1,0,0,0
58761,Zycie rodzinne,1971,88,NaN,6.0,14,NaN,0,0,0,1,0,0,0
58762,Zycie wewnetrzne,1987,86,NaN,6.5,8,NaN,0,0,0,0,0,0,0
58763,Zycie za zycie,1991,90,NaN,5.1,10,NaN,0,0,0,0,0,0,0
58764,Zyciorys,1975,46,NaN,3.6,5,NaN,0,0,0,1,0,0,0
58765,Zyklus von Kleinigkeiten,1999,86,NaN,6.0,5,NaN,0,0,0,1,0,0,0
58766,Zyosyuu syukeininn Maria,1995,75,NaN,3.7,19,R,0,0,0,0,0,0,0
58767,Zywot Mateusza,1967,80,NaN,5.4,31,NaN,0,0,0,1,0,0,0
58768,Zzikhimyeon jukneunda,2000,94,NaN,4.7,45,NaN,0,0,0,0,0,0,0
58769,Zzim,1998,101,NaN,4.5,14,NaN,0,0,0,0,0,0,0
58770,Zzyzx,2005,90,1000000.0,8.0,10,NaN,0,0,0,0,0,0,0
58771,alaska.de,2000,89,NaN,6.2,186,NaN,0,0,0,1,0,0,0
58772,barefootin',1987,3,NaN,5.7,6,NaN,0,1,0,0,0,0,1
58773,deadend.com,2002,120,NaN,6.9,53,NaN,0,0,0,1,0,0,0
58774,e-Dreams,2001,94,NaN,6.8,86,NaN,0,0,0,0,1,0,0
58775,eMale,2001,17,NaN,7.3,15,NaN,0,0,1,0,0,0,1
58776,eRATicate,2003,9,NaN,6.0,5,NaN,0,0,1,0,0,0,1
58777,eXXXorcismos,2002,78,NaN,4.2,11,NaN,0,0,0,1,0,0,0
58778,eXistenZ,1999,97,NaN,6.7,14742,R,0,0,0,1,0,0,0
58779,f2point8,2002,20,NaN,5.0,13,NaN,0,0,0,0,0,0,1
58780,f8,2001,13,NaN,7.6,7,NaN,0,1,0,0,0,0,1
58781,pURe kILLjoy,1998,87,NaN,5.2,6,NaN,0,0,0,0,0,0,0
58782,sIDney,2002,15,NaN,7.0,8,NaN,1,0,0,0,0,0,1
58783,tom thumb,1958,98,NaN,6.5,274,NaN,0,1,0,0,0,0,0
58784,www.XXX.com,2003,105,NaN,1.1,12,NaN,0,0,0,1,0,1,0
58785,www.hellssoapopera.com,1999,100,NaN,6.6,5,NaN,0,0,0,0,0,0,0
58786,xXx,2002,132,85000000.0,5.5,18514,PG-13,1,0,0,0,0,0,0
58787,xXx: State of the Union,2005,101,87000000.0,3.9,1584,PG-13,1,0,0,0,0,0,0

Wydaje się, że filmów jest ponad 58 tysięcy. Dla każdego z nich, w kolumnach, mamy dostępny szereg interesujących informacji. Spróbuj się domyślić, co oznaczają dane w poszczególnych kolumnach.

## Zmień kolumnę na listę

Żeby wyświetlić zawartość jednej kolumny, wystarczy podać jej nazwę w nawiasie kwadratowym (i oczywiście w cudzysłowiu!):

In [4]:
filmy['title']

0                                                        $
1                                        $1000 a Touchdown
2                                   $21 a Day Once a Month
3                                                  $40,000
4                                 $50,000 Climax Show, The
5                                                    $pent
6                                                  $windle
7                                                     '15'
8                                                      '38
9                                                  '49-'17
10                                                     '68
11                                  '94 du bi dao zhi qing
12                                       '?' Motorist, The
13                                                     'A'
14                                            'A' gai waak
15                                   'A' gai waak juk jaap
16                                        'Breaker' Morant
17        'Bullitt': Steve McQueen's Commitment to Reality
18                                   'Crocodile' Dundee II
19                                                     'E'
20                              'El Chicko' - der Verdacht
21                                                 'G' Men
22                                             'Gator Bait
23                           'Gator Bait II: Cajun Justice
24                                        'High Sign', The
25                             'Hukkunud Alpinisti' hotell
26                                     'Hyp-Nut-Tist', The
27                                               'I Do...'
28                               'I Know Where I'm Going!'
29         'Java Madness' formerly titled 'Coffee Madness'
                               ...
58758                               Zwoele zomeravond, Een
58759                                    Zwolnieni z zycia
58760    Zycie jako smiertelna choroba przenoszona drog...
58761                                       Zycie rodzinne
58762                                     Zycie wewnetrzne
58763                                       Zycie za zycie
58764                                             Zyciorys
58765                             Zyklus von Kleinigkeiten
58766                             Zyosyuu syukeininn Maria
58767                                       Zywot Mateusza
58768                                Zzikhimyeon jukneunda
58769                                                 Zzim
58770                                                Zzyzx
58771                                            alaska.de
58772                                          barefootin'
58773                                          deadend.com
58774                                             e-Dreams
58775                                                eMale
58776                                            eRATicate
58777                                         eXXXorcismos
58778                                             eXistenZ
58779                                             f2point8
58780                                                   f8
58781                                         pURe kILLjoy
58782                                               sIDney
58783                                            tom thumb
58784                                          www.XXX.com
58785                               www.hellssoapopera.com
58786                                                  xXx
58787                              xXx: State of the Union
Name: title, Length: 58788, dtype: object

Każdą kolumnę możemy zamienić na listę, korzystając ze znanej nam funkcji `list()`.

In [5]:
tytuly = list(filmy['title'])
lata = list(filmy['year'])
dlugosci = list(filmy['length'])
oceny = list(filmy['rating'])

## Najdłuższy film świata

Powiedzmy, że chcemy dowiedzieć się, ile trwa najdłuższy film w naszym zbiorze danych. Jak to zrobić? Skorzystajmy ze znanej nam już funkcji `max()`

In [6]:
max(dlugosci)

5220

Czy to możliwe? 5220 minuty daje jakieś 87 godzin czyli ponad trzy dni. Spróbujmy sprawdzić, jaki tytuł ma film o najdłuższym czasie trwania. Jak to sprawdzić? Najpierw musimy znaleźć indeks najdłuższej długości na liście długości. Skorzystamy w tym celu z metody `index()` a wynik umieścimy w zmiennej `najdluzszy`.

In [7]:
najdluzszy = dlugosci.index(max(dlugosci))
najdluzszy

11936

Widzimy, że poszukujemy filmu, który ma indeks 11936. Jak znaleźć jego tytuł? Wystarczy zmienną `najdłuższy` umieścić w nawiasie kwadratowym.

In [8]:
tytuly[najdluzszy]

'Cure for Insomnia, The'

To niesamowite, ale ten film na prawdę powstał i na prawdę trwa 87 godzin. Więcej info o nim możesz znaleźć na wikipedii: <https://en.wikipedia.org/wiki/The_Cure_for_Insomnia>

## Najlepszy i najgorszy film świata

W porządku. W ten sam sposób spróbujemy teraz znaleźć najlepszy i najgorszy film w naszej bazie. Wykorzystamy do tego celu listę `oceny`. Pozostałe kroki są dokładnie takie same jak powyżej (z wyjątkiem funkcji `min()` w jednym miejscu). Prześledź poniższy kod i upewnij się, że wszystko rozumiesz.

In [9]:
najlepszy_ocena = max(oceny)
najlepszy_indeks = oceny.index(najlepszy_ocena)
najlepszy_tytul = tytuly[najlepszy_indeks]

najgorszy_ocena = min(oceny)
najgorszy_indeks = oceny.index(najgorszy_ocena)
najgorszy_tytul = tytuly[najgorszy_indeks]

print('Najlepszy film do 2005 roku to', najlepszy_tytul)
print('Jego ocena to', najlepszy_ocena)

print('Najgorszy film do 2005 roku to', najgorszy_tytul)
print('Jego ocena to', najgorszy_ocena)

Najlepszy film do 2005 roku to Dimensia Minds Trilogy: The Hope Factor
Jego ocena to 10.0
Najgorszy film do 2005 roku to 20/20 Vision
Jego ocena to 1.0